### PR TITLE
Upstream miscellaneous helper files

### PR DESCRIPTION
**Pull request by jccleaver**
Bash completion script (from orig author)
Sample systemd service unit file

---
This change is [Reviewable](https://reviewable.io/reviews/packetsar/radiuid/42)

### CODE REVIEW

**Comment by PackeTsar** [comment]
These are just bash files for easy review? Do we want to modify the installer to copy these files instead of them coming from inside the source? Otherwise we have to maintain two copies of the same thing.

**Comment by jccleaver** [comment]
> These are just bash files for easy review? Do we want to modify the installer to copy these files instead of them coming from inside the source? Otherwise we have to maintain two copies of the same thing.

Ah.. my apologies, I didn't realize these were dropped internally from the main script itself. 

If the intent is to keep an install process integrated within the script, it doesn't make sense to break them back out I suppose. It might remain a bit confusing for those coming from a traditional packaging perspective, though.

**Comment by PackeTsar** [comment]
Yea they are dropped from the main script (which is a horrible practice as I now realize)

RadiUID was one of my first ever programming projects, not that I'm all that much greater at it now...

**Comment by jccleaver** [comment]
I think just a quick call-out in the README's OS install section noting a) that, and b) where it places files would probably be good enough.

**Comment by PackeTsar** [comment]
I agree. Good idea.

**Pull request closed without merging**
